-- MySQL Script generated by MySQL Workbench
-- 02/17/17 14:13:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema myapp
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `myapp` ;

-- -----------------------------------------------------
-- Schema myapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myapp` DEFAULT CHARACTER SET utf8 ;
USE `myapp` ;

-- -----------------------------------------------------
-- Table `myapp`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myapp`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `lastname` VARCHAR(100) NULL,
  `birthday` DATE NOT NULL,
  `email` VARCHAR(70) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `newsletter` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myapp`.`Team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myapp`.`Team` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `creationDate` DATE NOT NULL,
  `code` VARCHAR(80) NOT NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Team_User1_idx` (`idUser` ASC),
  CONSTRAINT `fk_Team_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `myapp`.`User` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myapp`.`UserTeam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myapp`.`UserTeam` (
  `idUser` INT NOT NULL,
  `idTeam` INT NOT NULL,
  PRIMARY KEY (`idUser`, `idTeam`),
  INDEX `fk_User_has_Team_Team1_idx` (`idTeam` ASC),
  INDEX `fk_User_has_Team_User_idx` (`idUser` ASC),
  CONSTRAINT `fk_User_has_Team_User`
    FOREIGN KEY (`idUser`)
    REFERENCES `myapp`.`User` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_User_has_Team_Team1`
    FOREIGN KEY (`idTeam`)
    REFERENCES `myapp`.`Team` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myapp`.`Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myapp`.`Payment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` TINYINT(1) NOT NULL,
  `transactionId` VARCHAR(45) NOT NULL,
  `amount` DECIMAL(15,2) NOT NULL,
  `completed` DATE NOT NULL,
  `idTeam` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Payment_Team1_idx` (`idTeam` ASC),
  CONSTRAINT `fk_Payment_Team1`
    FOREIGN KEY (`idTeam`)
    REFERENCES `myapp`.`Team` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
